### ISSUE TITLE
Approximate baseline code release date?

### ISSUE THREAD

**Issue by mkumar10** [lil-lab/touchdown#1]

**Comment by mkumar10** [comment]
@howard50b bump

**Comment by howard50b** [comment]
Hi @mkumar10, sorry to have missed the message. The code will be released this week. Sorry for the late reply!

**Comment by howard50b** [comment]
Hi @mkumar10, due to some unexpected technical issue, I wasn't able to have it released last week. I'm shooting for this Wednesday. Sorry again for the delay.

**Comment by yoavartzi** [comment]
Please see the baselines described in the Retouchdown paper:
https://arxiv.org/pdf/2001.03671.pdf
That are available here:
https://github.com/google-research/valan
