### ISSUE TITLE
Baseline code for RConcat and GA

### ISSUE THREAD

**Issue by anirban-code-to-live** [lil-lab/touchdown#2]
The baseline code for the navigation task - **RConcat** and **GA** seems to be missing. It'd be really helpful if those are added to this repo. Thanks in advance.

**Comment by yoavartzi** [comment]
Please see the baselines described in the Retouchdown paper:
https://arxiv.org/pdf/2001.03671.pdf
That are available here:
https://github.com/google-research/valan
