### ISSUE TITLE
loading images

### ISSUE THREAD

**Issue by raphael-sch** [lil-lab/touchdown#3]
Hello, 

in the following lines https://github.com/lil-lab/touchdown/blob/1621d60e5797417fa43b759d34357ab9586a9d64/sdr/loader.py#L47
https://github.com/lil-lab/touchdown/blob/1621d60e5797417fa43b759d34357ab9586a9d64/sdr/loader.py#L150
you load the images from the image directory. Are these numpy arrays of the full images or the ResNet features? In the paper you mention, that the features are released, but I can't find them. Neither on this github nor in the datasets on streetlearn.cc.

**Comment by howard50b** [comment]
Hi, 

Thanks for reaching out! This is for the image features we released initially. We couldn't share the actual panoramic images until recently (so we released the features instead) but now you can access (need to fill out a request form) the actual panoramic images and the code here: 

Code: https://github.com/google-research/valan
Data: https://sites.google.com/view/streetlearn/dataset?authuser=0

The code for loading the feature is outdated and we'll update it.

**Comment by yangsikai** [comment]
Hello,
    Thank you for the field of research results, I became very interested in this field. I saw that you updated the touchdown code in the valan model, and I also signed the agreement and got the touchdown instruction data set, but I didn’t know how to run it. I hope you  explain it if you have time.

**Comment by yoavartzi** [comment]
@yangsikai  If you are asking about running VALAN, we recommend posting on their repository or emailing the authors.
